# Generated by Django 3.2.16 on 2026-09-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id_organizer', models.AutoField(primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id_quest', models.AutoField(primary_key=True, serialize=False)),
                ('quest_name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('preview_pic', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MQH_app.genre')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MQH_app.organizer')),
            ],
            options={
                'db_table': 'quest',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('in_date', models.DateField(auto_now_add=True, db_column='in_date')),
                ('active_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MQH_app.quest')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MQH_app.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
                'unique_together': {('quest', 'booking_date')},
            },
        ),
    ]
