# Generated by Django 3.2.16 on 2022-12-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQH_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True},
        ),
    ]
