# Generated by Django 3.2.16 on 2022-12-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQH_app', '0002_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': False},
        ),
    ]
