# Generated by Django 3.2.16 on 2022-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id_organizer', models.AutoField(primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'organizer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id_quest', models.AutoField(primary_key=True, serialize=False)),
                ('quest_name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('preview_pic', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'quest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
